### ISSUE TITLE
drop cme_utils as requirement

### ISSUE THREAD

**Issue by jennyfothergill** [cmelab/planckton#2]
we only use cme_utils for:

 `from cme_utils.manip.ff_from_foyer import set_coeffs` which should be replaced by `foyer.Forcefield.apply` 

and `from cme_utils.manip.convert_rigid import init_wrapper`. Not sure what to do about this one, but it'll need updating I assume.

**Comment by mikemhenry** [comment]
We talked about `init_wrapper` on slack but just to document this better, that wrapper is used to make rigid bodies work by allowing users in the hoomdxml to set the rigid body id. It has a few limitations, the most annoying one is that all unique rigid bodies must have the same orientation, which is why when we use packmol, we fix the molecule orientations.
